import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { CareerHeroContainer } from "../../container";
import CareerContainer from "../../container/CareerContainer/index";
import Footer from "../../container/Footer";
import SingleCareerHeroContainer from "../../container/SingleCareerHeroContainer";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ScholarX - Careers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SingleCareerHeroContainer />
      <CareerContainer />
      <Footer />
    </>
  );
};

export default Home;
