export type StackPropsType = {
  children?: JSX.Element | JSX.Element[] | string;
  onClick?: () => void;
  width?: string;
  height?: string;
  minHeight?: string;
  maxHeight?: string;
  minWidth?: string;
  maxWidth?: string;
  gap?: string;
  m?: string;
  p?: string;
  direction?: string;
  color?: string;
  bgColor?: string;
  flexWrap?: string;
  sm_flexWrap?:string;
  md_flexWrap?:string;
  textAlign?: string;
  alignItems?: string;
  justifyContent?: string;
  sm_direction?: string;
  md_direction?: string;
  lg_direction?: string;
  sm_alignItems?: string;
  md_alignItems?: string;
  lg_alignItems?: string;
  sm_textAlign?: string;
  md_textAlign?: string;
  sm_gap?: string;
  md_gap?: string;
  sm_m?: string;
  md_m?: string;
  sm_p?: string;
  md_p?: string;
  sm_width?: string;
  md_width?: string;
  xsm_width?: string;
  xm?: string;
  xxm?: string;
  sm_height?: string;
  md_height?: string;
  rounded?: string;
  className?: string;
  sm_justifyContent?: string;
  borderwidth?: string;
  borderstyle?: string;
  bordercolor?: string;
  key?: number;
  md_justifyContent?:string;
}&any;
