import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { CareerHeroContainer } from "../../container";
import NoCareerContainer from "../../container/NoCareerContainer/index";
import Footer from "../../container/Footer";

import NoCareerHeroContainer from "../../container/NoCareerHeroContainer";import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NoCareerHeroContainer />
      <NoCareerContainer />
      <Footer />
    </>
  );
};

export default Home;
