import React from "react";
import { ReferformContainer, CareerHeroContainer } from "../../container";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Footer from "../../container/Footer";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CareerHeroContainer />
      <ReferformContainer />
      <Footer />
    </>
  );
};

export default Home;